### ISSUE TITLE
Compilation error on recursive function when using slicing in recursive function call

### ISSUE THREAD

**Issue by adrian-lison** [stan-dev/cmdstan#1109] opened 2022-07-22 21:11 UTC
#### Summary:
Compilation error on recursive function when using slicing in recursive function call.

#### Description:
I get a weird compilation error when using a recursive function definition that has a slice/range index in the recursive function call.

#### Reproducible Steps:
Just take the example from the stan user's guide:
```
matrix matrix_pow(matrix a, int n);

matrix matrix_pow(matrix a, int n) {
  if (n == 0) {
    return diag_matrix(rep_vector(1, rows(a)));
  } else {
    return a *  matrix_pow(a, n - 1);
  }
}
```
and add some range index to the first argument in the recursive function call, e.g. (only last row changed):
```
matrix matrix_pow(matrix a, int n);

matrix matrix_pow(matrix a, int n) {
  if (n == 0) {
    return diag_matrix(rep_vector(1, rows(a)));
  } else {
    return a *  matrix_pow(a[1:rows(a), 1:cols(a)], n - 1);
  }
}
```
Then include a call to this function somewhere in a valid stan model and try to compile.

#### Current Output:
The following error arises during compilation (output shortened):
```
...
In file included from ...usr/include/c++/v1/__memory/base.h:15:
...usr/include/c++/v1/type_traits:711:44: fatal error:
recursive template instantiation exceeded maximum depth of 1024
{typedef typename remove_volatile<typename remove_const<_Tp>::type>::type type;};
... [lots of stack trace]
```

#### Expected Output:
Normal compilation.

#### Additional Information:
Error can be avoided by assigning the sliced `a[1:rows(a), 1:cols(a)]` to a new variable `b` and then using `b` in the recursive function call instead. This observation makes it look to me like a syntactic issue really.

#### Current Version:
v2.30.0
I compiled using `cmdstanr`.

**Comment by adrian-lison** [comment] 2022-07-22 21:32
Sorry if this fits better for `stanc3`, can repost issue there if this is the case.

**Comment by WardBrian** [comment] 2022-07-22 21:36
I believe this is a duplicate of https://github.com/stan-dev/stanc3/issues/1224

In the mean time, you can allow this to compile by wrapping the recursive call’s arguments in `to_matrix` or with the assignment you mention. Both of these work because they force the C++ compiler to halt further template expansion by evaluating the Eigen expression returned by slicing

**Comment by WardBrian** [comment] 2022-07-23 16:57
Closing this in favor of the other, but I think your description of the issue is more clear so I am going to update the other's title. Thanks for reporting!

**Closed by WardBrian** 2022-07-23 16:57 UTC
