### ISSUE TITLE
libsundials_nvecserial.a and libsundials_cvodes.a files issue

### ISSUE THREAD

**Issue by MattNewest5** [stan-dev/cmdstan#648] opened 2018-10-01 06:45 UTC
#### Summary:
libsundials_nvecserial.a and libsundials_cvodes.a do not exist.

#### Description:
Hi, when I run a .jl file, I got the next message:
"An error occurred while compiling the Stan program.

Please check your Stan program in variable 'schools8' and the contents of C:/Users/me/Desktop/tm
p/tmp/tmp/schools8.exe_build.log."

schools8.exe_build.log said:
"uname: not found
uname: not found
g++.exe: error: stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a: No such file or directory
g++.exe: error: stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a: No such file or directory
make: *** [C:/Users/me/Desktop/tmp/tmp/tmp/schools8.exe] Error 1"

Do you know how can I fix this? I looked in my cmdstan folder and libsundials_nvecserial.a and libsundials_cvodes.a do not exist anywhere, so is that an error? I mean those files should be inside stan/lib/stan_math/lib/cvodes_2.9.0/lib, but they do not exist, are they missing?

#### Additional Information:
OS: Windows 10 CmdStan: cmdstan-2.17.1 Rtools: 3.4 Julia: 0.64, I tried the 2.18.0 version of cmdstan and it did not work well.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment] 2018-10-01 18:14
duplicate of #640;  closing this one and merging extra information into existing issue

**Closed by bob-carpenter** 2018-10-01 18:14 UTC
