### ISSUE TITLE
Update manual to specify that the new compiler make option is CXX (old title: Compilation does not honour setting CC in the main makefile)

### ISSUE THREAD

**Issue by chmue** [stan-dev/cmdstan#566] opened 2017-09-06 15:57 UTC
#### Summary:
Compilation does not honour setting CC in the main makefile. The value seems to be overwritten by the default compiler for the stan Math library.

#### Description:
I am trying to build cmdstan on a system with no clang compilers installed.

Although `CC` is set to `g++` in the main makefile (`./makefile`; the default), the actual value of `CC` that make uses to compile is `clang++`.

I *think* I tracked the problem to `./stan/lib/stan_math/make/default_compiler_options` where `CC` is set to `clang++`. When I change the line in that file to `CC=g++`, make correctly uses `g++` as the compiler.

#### Reproducible Steps:
```sh
wget https://github.com/stan-dev/cmdstan/releases/download/v2.17.0/cmdstan-2.17.0.tar.gz
tar -xf cmdstan-2.17.0.tar.gz
cd cmdstan-2.17.0
make build
```

#### Current Output:

```
clang++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src
-I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -stdlib=libc++ -Wno-unused-function -Wno-uninitialized -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -o bin/cmdstan/stanc.o src/cmdstan/stanc.cpp
make: clang++: Command not found
make: *** [bin/cmdstan/stanc.o] Error 127
```

#### Expected Output:
```
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src
-I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -stdlib=libc++ -Wno-unused-function -Wno-uninitialized -DNO_FPRINTF_OUTPUT -pipe  -c -O3 -o bin/cmdstan/stanc.o src/cmdstan/stanc.cpp
*** compiling ***
```

#### Additional Information:
```
make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

#### Current Version:
v2.17.0

**Comment by sakrejda** [comment] 2017-09-06 16:31
I just ran into some of the order-dependency in the math library itself, I wonder if we shouldn't be building all these compiler options separately and then making it possible for the final makefile to pick and choose.

**Comment by syclik** [comment] 2017-09-06 16:56
Just a few quick notes: we've switched to using `CXX`. And... I believe you
should still be able to create a `make/local` file with your customizations
that should take priority over the makefile. There's no reason to adjust
the top level makefile.

I'm going to verify later this afternoon and report back.

**Comment by chmue** [comment] 2017-09-07 15:26
Thanks @syclik!

I see from section B.2 in the manual that I should have used `make/local` to set my options. The switch to `CXX` is not yet in the manual though. I will experiment with setting `CC` and/or `CXX` in the correct way and report back.

**Comment by syclik** [comment] 2017-09-07 15:38
Just verified that setting `CXX` in `make/local` will build with that compiler. 

Sorry about the manual -- we didn't fix it before the release. I'll open up an issue for fixing the manual for the next release.

**Comment by syclik** [comment] 2017-09-07 15:39
On second thought, I'm just gonna hijack this issue and when we update the manual, we'll close this issue.

**Comment by torsti** [comment] 2017-09-08 07:06
Sorry to jump in, but this seemed very much related to the original topic and it probably doesn't need it's own issue (under `cmdstan` anyway, though maybe math should be using `CXX` too):

To compile the `cmdstan-2.17.0.tar.gz` release with `g++` I had to set both `CXX` and `CC` (`CC` only works too)  to `g++` in `make/local`, because without setting `CC` `make/detect_cc` from the bundled `math` will think `clang++` is the compiler and add `-stdlib=libc++` to `CXXFLAGS` and `g++` complains. (`g++: error: unrecognized command line option ‘-stdlib=libc++’`).

I tested with g++ 6.3 and 7.2.

**Comment by syclik** [comment] 2017-09-08 10:55
Ah. That is indeed something worth a separate issue and will need to be fixed at the math library too. 

Here's a recent discussion: http://discourse.mc-stan.org/t/clang-ubuntu-problems/1761/1

**Comment by sakrejda** [comment] 2017-09-08 11:26
Ok, confirmed both that it works with CC modified and fails with CXX-only modified.  

```
krzysztof@hagrid:~/packages/cmdstan-develop$ make examples/bernoulli/bernoulli
--- Linking C++ model ---
g++ -Wall -I . -isystem stan/lib/stan_math/lib/eigen_3.3.3 -isystem stan/lib/stan_math/lib/boost_1.64.0 -isystem stan/lib/stan_math/lib/cvodes_2.9.0/include -std=c++1y -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I src -I stan/src -isystem stan/lib/stan_math/ -DEIGEN_NO_DEBUG -DFUSION_MAX_VECTOR_SIZE=12 -stdlib=libc++ -Wno-unused-function -Wno-uninitialized -DNO_FPRINTF_OUTPUT -pipe   -O3 -o examples/bernoulli/bernoulli src/cmdstan/main.cpp -include examples/bernoulli/bernoulli.hpp stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/cvodes_2.9.0/lib/libsundials_cvodes.a
g++: error: unrecognized command line option ‘-stdlib=libc++’
make/models:10: recipe for target 'examples/bernoulli/bernoulli' failed
make: *** [examples/bernoulli/bernoulli] Error 1
```

**Comment by sakrejda** [comment] 2017-09-08 11:26
@syclik @torsti I'm making a separate issue since this one is getting muddled, we can close this when the manual says something coherent.

**Comment by seantalts** [comment] 2017-09-20 01:26
I'm confused - when I do a fresh clone of `cmdstan` and set CC to g++ with `echo "CC=g++" > make/local` it works just fine - I don't see any errors. As far as I know this is the correct way to change this setting? 

I will also remove the default compiler settings from the toplevel makefile - I think that should have come out in the commit when we changed to source the default compiler options from math.

**Comment by sakrejda** [comment] 2017-09-21 15:46
You guys switched CmdStan to CXX so it's confusing for people to set CC  If you just set CXX it won't work.  CXX is set from CC in the makefiles from Math.  This can all work it's just really convoluted. I'd like to unconvolute...

**Comment by seantalts** [comment] 2017-09-21 16:28
What do you mean we switched it to CXX? I believe the interface has stayed the same, except that people were previously setting things in `makefile` instead of `make/local`, and the former won't work anymore.

**Comment by sakrejda** [comment] 2017-09-21 16:34
github ate my response: Check the full issue above, especially @torsti comment.

**Comment by fredRos** [comment] 2017-11-20 14:57
I encountered the same error on windows with cmdstan2.17. I followed the manual and install the latest stable Rtools that comes with gcc4.6.3. It additionally failed because the option `-std=c++1y` is not recognized by this old compiler and `--stlib=libc++` is set in `detect_cc`.. I suppose these are other remnants of focusing on some version of clang. In the end, I couldn't compile  the example mode because in the linking step, it can't link to `libsundials_nvecserial.a` and `libsundials_cvodes.a`. Any ideas how to fix that?

I think the bottom line is that cmdstan on windows needs some more testing and an update of the manual

**Comment by seantalts** [comment] 2017-12-08 18:58
The RTools 3.3 and up have gcc 4.9.3.

**Comment by seantalts** [comment] 2017-12-11 17:41
Ah, I think I see what you're saying - you want to use gcc's builtin stdlib instead of libc++ from the llvm team. We should probably add a flag for that in `make/local`.

**Comment by fredRos** [comment] 2017-12-11 19:56
Well not quite. In my opinion `make` should detect that I'm not using
clang on mac but rtools with gcc on windows. Right now it doesn't build
at all. Choosing stdlibc++ is not a matter of preference here.


Am 11.12.2017 um 18:41 schrieb seantalts:

**Comment by seantalts** [comment] 2017-12-11 20:11
What error messages do you get if you put `CC=g++` in `make/local`?

You can also open an issue for automatically detecting which compilers you have installed - there's probably some way we could hack `make` to do that by trying each compiler command and seeing which ones exist, or something like that. We take pull requests, too!

**Comment by davidmanheim** [comment] 2019-02-10 07:46
Just to note:
I had this error in Windows 10, and created make/local with:
CC=g++ 
CXX=g++
and ran 'make clean-all', then reran make, and it installed fine..

**Closed** 2019-09-16 17:20 UTC
