### ISSUE TITLE
Backslash in paths generates C++ error 

### ISSUE THREAD

**Issue by danmrc** [stan-dev/cmdstan#720] opened 2019-08-06 01:18 UTC
#### Summary:

I am using cmdStan in Julia in Windows 10. I apologize if this is a Julia related error. What happens is that when Stan generates the file for C++ it uses backslash in the file path, and this makes C++ throw an error.

#### Description:

I am not sure if this is an issue with cmdstan or stan.jl, so if I am opening the issue in the wrong place I apologize.

I am using Julia 1.0.0, cmdStan 2.20.0 and all packages on Julia are up to date. I am using Windows and did the whole work of using RTools to make cmdStan work.

I am using the Bernoulli example that is [in the documentation](https://stanjulia.github.io/Stan.jl/latest/WALKTHROUGH.html). It throws an error and the log says:

```
C:/Users/User/Documents/GitHub/Julia-Para-Economistas/tmp/bernoulli.hpp:21:37: error: incomplete universal character name \U
     reader.add_event(13, 11, "end", "C:\Users\User\Documents\GitHub\Julia-Para-Economistas\tmp\bernoulli.stan");
```

The issue is that for the paths, like `"C:\Users\User\Documents\GitHub\Julia-Para-Economistas\tmp\bernoulli.stan"`, stan is using backslash. Going in the bernoulli.hpp file and changing the backslash in the paths to slash solves the problem. 

So, the question is how do I make cmdStan make this change automatically? Is this an Julia issue or a cmdStan problem?

#### Reproducible Steps:

It is in Julia:

```
using CmdStan
using Mamba
using Cairo

set_cmdstan_home!("C:\\Users\\User\\Downloads\\cmdstan-2.20.0")

bernoullistanmodel = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
    y ~ bernoulli(theta);
}"

stanmodel = Stanmodel(name="bernoulli", model=bernoullistanmodel)

bernoullidata = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

rc, sim1 = stan(stanmodel, [bernoullidata], 
"C:\\Users\\User\\Documents\\GitHub\\Julia-Para-Economistas")
```

You can use Stan instead of CmdStan packages, both generate the same error

#### Current Output:

Julia throws _An error has occurred_. The log shows the following error:

```C:/Users/User/Documents/GitHub/Julia-Para-Economistas/tmp/bernoulli.hpp:21:37: error: incomplete universal character name \U
     reader.add_event(13, 11, "end", "C:\Users\User\Documents\GitHub\Julia-Para-Economistas\tmp\bernoulli.stan");
```

#### Expected Output:

Model should be estimated correctly, as it is when I change the paths by hand. 

#### Additional Information:

Maybe I did something wrong when I installed it? It took me a while to get cmdStan to find g++ in RTools so it could compile something. I am not sure if I did something wrong during installation and if it is necessary, I can describe every step I took during instalation. 

#### Current Version:
v2.20.0

Thanks in advance!

**Comment by seantalts** [comment] 2019-08-06 08:22
It looks like you're in roughly the right place - I think this is probably
a bug in the Stan compiler, though I'm surprised it's only surfacing now...
I'll look into it - there's a good chance it will be fixed when we switch
to stanc3.

**Comment by seantalts** [comment] 2019-08-06 16:42
Yeah, this looks like a bug in CmdStan that only occurs with absolute paths on Windows. It doesn't look like it's new in 2.20.0 - I can reproduce it in 2.19.1 as well. Thanks for reporting!

**Closed** 2019-09-26 18:53 UTC
Labels: bug
