### ISSUE TITLE
compilation error with RK45 integration code

### ISSUE THREAD

**Issue by dhrunia** [stan-dev/cmdstan#840] opened 2020-03-12 13:07 UTC
#### Summary:
Compiling stan code for inferring parameters of a couple ODE system using RK45 is throwing some errors related to underlying `C` code

#### Description:
I am trying to infer some parameters of a coupled ODE system using stan's built-in RK45 integrator. Compiling the stan code fails with the below error:
```
In file included from stan/lib/stan_math/stan/math/prim/fun/divide_columns.hpp:7,
                 from stan/lib/stan_math/stan/math/prim/fun/gp_exp_quad_cov.hpp:7,
                 from stan/lib/stan_math/stan/math/prim/fun/cov_exp_quad.hpp:6,
                 from stan/lib/stan_math/stan/math/prim/fun.hpp:51,
                 from stan/lib/stan_math/stan/math/prim.hpp:10,
                 from stan/lib/stan_math/stan/math/rev.hpp:11,
                 from stan/lib/stan_math/stan/math.hpp:148,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/lib/stan_math/stan/math/prim/fun/divide.hpp: In instantiation of ‘stan::return_type_t<T1, T2> stan::math::divide(const T1&, const T2&) [with T1 = Eigen::Matrix<stan::math::var, 1, -1>; T2 = int; stan::return_type_t<T1, T2> = stan::math::var]’:
/home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:892:17:   required from ‘T__ szr_prpgtn_rk45_model_namespace::szr_prpgtn_rk45_model::log_prob(std::vector<T_l>&, std::vector<int>&, std::ostream*) const [with bool propto__ = false; bool jacobian__ = false; T__ = stan::math::var; std::ostream = std::basic_ostream<char>]’
stan/src/stan/model/model_base_crtp.hpp:153:29:   required from ‘stan::math::var stan::model::model_base_crtp<M>::log_prob(std::vector<stan::math::var>&, std::vector<int>&, std::ostream*) const [with M = szr_prpgtn_rk45_model_namespace::szr_prpgtn_rk45_model; std::ostream = std::basic_ostream<char>]’
stan/src/stan/model/model_base_crtp.hpp:149:20:   required from here
stan/lib/stan_math/stan/math/prim/fun/divide.hpp:23:14: error: could not convert ‘Eigen::MatrixBase<Derived>::operator/(const T&) const [with T = int; Derived = Eigen::Matrix<stan::math::var, 1, -1>; typename Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::promote_scalar_arg<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::scalar_quotient_op<typename Eigen::internal::traits<T>::Scalar, T> > >::value>::type>, const Derived, const typename Eigen::internal::plain_constant_type<Derived, typename Eigen::internal::promote_scalar_arg<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::scalar_quotient_op<typename Eigen::internal::traits<T>::Scalar, T> > >::value>::type>::type> >::type = const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<stan::math::var, stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1> > >]((* & y))’ from ‘Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<stan::math::var, stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1> > > >::type’ {aka ‘const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<stan::math::var, stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1> > >’} to ‘stan::return_type_t<Eigen::Matrix<stan::math::var, 1, -1, 1, 1, -1>, int>’ {aka ‘stan::math::var’}
   23 |   return x / y;
      |              ^
      |              |
      |              Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<stan::math::var, stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1> > > >::type {aka const Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<stan::math::var, stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<stan::math::var>, const Eigen::Matrix<stan::math::var, 1, -1> > >}
In file included from stan/src/stan/model/indexing.hpp:7,
                 from stan/src/stan/model/model_header.hpp:15,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/src/stan/model/indexing/lvalue.hpp: In instantiation of ‘void stan::model::assign(T&, const stan::model::nil_index_list&, const U&, const char*, int) [with T = Eigen::Matrix<stan::math::var, 1, -1>; U = stan::math::var]’:
/home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:891:15:   required from ‘T__ szr_prpgtn_rk45_model_namespace::szr_prpgtn_rk45_model::log_prob(std::vector<T_l>&, std::vector<int>&, std::ostream*) const [with bool propto__ = false; bool jacobian__ = false; T__ = stan::math::var; std::ostream = std::basic_ostream<char>]’
stan/src/stan/model/model_base_crtp.hpp:153:29:   required from ‘stan::math::var stan::model::model_base_crtp<M>::log_prob(std::vector<stan::math::var>&, std::vector<int>&, std::ostream*) const [with M = szr_prpgtn_rk45_model_namespace::szr_prpgtn_rk45_model; std::ostream = std::basic_ostream<char>]’
stan/src/stan/model/model_base_crtp.hpp:149:20:   required from here
stan/src/stan/model/indexing/lvalue.hpp:32:5: error: no match for ‘operator=’ (operand types are ‘Eigen::Matrix<stan::math::var, 1, -1>’ and ‘const stan::math::var’)
   32 |   x = y;
      |   ~~^~~
In file included from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Core:437,
                 from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:13,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:148,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:206:33: note: candidate: ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>&) [with _Scalar = stan::math::var; int _Rows = 1; int _Cols = -1; int _Options = 1; int _MaxRows = 1; int _MaxCols = -1]’
  206 |     EIGEN_STRONG_INLINE Matrix& operator=(const Matrix& other)
      |                                 ^~~~~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:206:57: note:   no known conversion for argument 1 from ‘const stan::math::var’ to ‘const Eigen::Matrix<stan::math::var, 1, -1>&’
  206 |     EIGEN_STRONG_INLINE Matrix& operator=(const Matrix& other)
      |                                           ~~~~~~~~~~~~~~^~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:223:33: note: candidate: ‘template<class OtherDerived> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = OtherDerived; _Scalar = stan::math::var; int _Rows = 1; int _Cols = -1; int _Options = 1; int _MaxRows = 1; int _MaxCols = -1]’
  223 |     EIGEN_STRONG_INLINE Matrix& operator=(const DenseBase<OtherDerived>& other)
      |                                 ^~~~~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:223:33: note:   template argument deduction/substitution failed:
In file included from stan/src/stan/model/indexing.hpp:7,
                 from stan/src/stan/model/model_header.hpp:15,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/src/stan/model/indexing/lvalue.hpp:32:5: note:   ‘const stan::math::var’ is not derived from ‘const Eigen::DenseBase<Derived>’
   32 |   x = y;
      |   ~~^~~
In file included from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Core:437,
                 from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:13,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:148,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:236:33: note: candidate: ‘template<class OtherDerived> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = OtherDerived; _Scalar = stan::math::var; int _Rows = 1; int _Cols = -1; int _Options = 1; int _MaxRows = 1; int _MaxCols = -1]’
  236 |     EIGEN_STRONG_INLINE Matrix& operator=(const EigenBase<OtherDerived> &other)
      |                                 ^~~~~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:236:33: note:   template argument deduction/substitution failed:
In file included from stan/src/stan/model/indexing.hpp:7,
                 from stan/src/stan/model/model_header.hpp:15,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/src/stan/model/indexing/lvalue.hpp:32:5: note:   ‘const stan::math::var’ is not derived from ‘const Eigen::EigenBase<Derived>’
   32 |   x = y;
      |   ~~^~~
In file included from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Core:437,
                 from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:13,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:148,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:243:33: note: candidate: ‘template<class OtherDerived> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::ReturnByValue<OtherDerived>&) [with OtherDerived = OtherDerived; _Scalar = stan::math::var; int _Rows = 1; int _Cols = -1; int _Options = 1; int _MaxRows = 1; int _MaxCols = -1]’
  243 |     EIGEN_STRONG_INLINE Matrix& operator=(const ReturnByValue<OtherDerived>& func)
      |                                 ^~~~~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:243:33: note:   template argument deduction/substitution failed:
In file included from stan/src/stan/model/indexing.hpp:7,
                 from stan/src/stan/model/model_header.hpp:15,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/src/stan/model/indexing/lvalue.hpp:32:5: note:   ‘const stan::math::var’ is not derived from ‘const Eigen::ReturnByValue<Derived>’
   32 |   x = y;
      |   ~~^~~
In file included from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Core:437,
                 from stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:13,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:148,
                 from stan/src/stan/model/model_header.hpp:4,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:281:13: note: candidate: ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>&&) [with _Scalar = stan::math::var; int _Rows = 1; int _Cols = -1; int _Options = 1; int _MaxRows = 1; int _MaxCols = -1]’
  281 |     Matrix& operator=(Matrix&& other) EIGEN_NOEXCEPT_IF(std::is_nothrow_move_assignable<Scalar>::value)
      |             ^~~~~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:281:32: note:   no known conversion for argument 1 from ‘const stan::math::var’ to ‘Eigen::Matrix<stan::math::var, 1, -1>&&’
  281 |     Matrix& operator=(Matrix&& other) EIGEN_NOEXCEPT_IF(std::is_nothrow_move_assignable<Scalar>::value)
      |                       ~~~~~~~~~^~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:392:13: note: candidate: ‘template<class OtherDerived> Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::RotationBase<OtherDerived, Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::ColsAtCompileTime>&) [with OtherDerived = OtherDerived; _Scalar = stan::math::var; int _Rows = 1; int _Cols = -1; int _Options = 1; int _MaxRows = 1; int _MaxCols = -1]’
  392 |     Matrix& operator=(const RotationBase<OtherDerived,ColsAtCompileTime>& r);
      |             ^~~~~~~~
stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Matrix.h:392:13: note:   template argument deduction/substitution failed:
In file included from stan/src/stan/model/indexing.hpp:7,
                 from stan/src/stan/model/model_header.hpp:15,
                 from /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45.hpp:3:
stan/src/stan/model/indexing/lvalue.hpp:32:5: note:   ‘const stan::math::var’ is not derived from ‘const Eigen::RotationBase<OtherDerived, -1>’
   32 |   x = y;
      |   ~~^~~
make: *** [make/program:44: /home/anirudh/hdisk/Academia/projects/vep.stan/szr_prpgtn_rk45] Error 1
```
There is no error in the derivative function passed to `integrated_ode_rk45` because I was able to compile and generate pseudo data using `generated quantities` block. But compilation fails on moving the integration to `model` or `transformed parameters` block for inference

#### Current Version:
stan version: v2.22
gcc version: 9.2.1

@maedoc has tested it also with gcc 8.3 but got the same error

**Comment by rok-cesnovar** [comment] 2020-03-12 13:12
Thanks for reporting. Is this is the official 2.22.1 release or clone from the repository?

**Comment by maedoc** [comment] 2020-03-12 13:13
Official 2.22.1 release

**Comment by rok-cesnovar** [comment] 2020-03-12 13:15
Thanks. In that case please try the following: 

- make clean-all
- add STANC2=true to make/local
- make build
- build your model

If this compiles, then its a stanc3 issue otherwise its mostly likely related to the changes in Stan Math.

**Comment by maedoc** [comment] 2020-03-12 13:24
The error persists; I deleted the hpp file, rebuilt the model as well.  I also checked than `stanc --help` options are fewer than with the newer version.

**Comment by rok-cesnovar** [comment] 2020-03-12 13:34
Ok, that significantly reduces the space of potential causes as its most likely the changes in the Math library. Either that or something that should be caught earlier by the Stan to C++ compiler but isnt.

Can you share your model or at least bits of it that are the cause?

The things I would try for now, before someone with mode knowledge responds:
- try the develop version of cmdstan and if that doesnt work
- try the develop version of cmdstan with and older version of stan math

**Comment by maedoc** [comment] 2020-03-12 13:38
Thanks for the tips.  It does compile with 2.19.1.  We can use that in the short term, and try to create a reproducer that can be shared.

**Comment by maedoc** [comment] 2020-03-12 13:54
A fresh clone of CmdStan (develop branch, f348bc1dbe8b) builds the model without error as well.  I am still running a git bisect, maybe the result would be useful anyway.

**Comment by rok-cesnovar** [comment] 2020-03-12 13:55
Fantastic. Yes, that would be very helpful. Thank you!

**Comment by maedoc** [comment] 2020-03-12 14:55
Bisect from v2.21.0 to v2.22.0 w/ the script
```bash
#!/bin/bash
echo 'STANC2=true' > make/local
git submodule update &> /dev/null
(cd stan && git submodule update) &> /dev/null
make clean-all &> /dev/null
make build -j6 &> /dev/null
rm -f model model.hpp &> /dev/null
make model &> /dev/null
```
says
```
running ./test_model.sh
30b37ce347a79eba128d16746030c30d74aec77b is the first bad commit
commit 30b37ce347a79eba128d16746030c30d74aec77b
Author: Stan Jenkins <mc.stanislaw@gmail.com>
Date:   Thu Dec 12 23:16:00 2019 -0500

    Updates the Stan submodule to 3140ac4.

:160000 160000 430b1b91cb1f5fe7398d6271a6c3d35ce9700b1b 3140ac444655ec96578d5d4a16e0f1325627a469 M	stan
```
I would guess some commit in the submodule would provide a more precise result, but I'm not sure how to do that properly.

**Comment by maedoc** [comment] 2020-03-12 14:57
I would suggest closing this issue, perhaps at next release.

**Closed** 2020-05-30 18:42 UTC
