### ISSUE TITLE
Eigen exception in v2.27.0

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/cmdstan#1022] opened 2021-06-10 22:39 UTC
#### Summary:
Model works fine in v2.26.1 but failed with Eigen exception in v2.27.0

#### Description:
[b6.stan](https://github.com/stan-dev/cmdstan/files/6634759/b6.stan.txt)

#### Reproducible Steps:

Maybe you can reproduce with [init-1-2ae51816ea745e.json.txt](https://github.com/stan-dev/cmdstan/files/6634764/init-1-2ae51816ea745e.json.txt) and [standata-2ae5182d43a9dc.json.txt](https://github.com/stan-dev/cmdstan/files/6634765/standata-2ae5182d43a9dc.json.txt)

#### Current Output:
```
stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/DenseBase.h:256: void Eigen::DenseBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >; Eigen::Index = long int]: Assertion `rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow to resize."' failed.
```

#### Expected Output:
Would be nice if model sampled.

#### Current Version:
v2.27.0

**Comment by andrjohns** [comment] 2021-06-11 14:18
I think I've tracked this down to a syntax error.

In the `transformed data` block you've defined the vector `truncPoints` as being size `numThresholds`, where `numThresholds` is the maximum value of the data:
```
transformed data {
  int numThresholds = max(outcome);
  ...
  vector[numThresholds] truncPoints = ordinalTruncPoints(outcome);
}
```

But in the `ordinalTruncPoints` function you've defined the number of thresholds as the maximum value - 1, and returned a vector of that size:
```
  ...
  int numOutcomes = max(outcome);
  ...
  int numThr = numOutcomes-1;
  vector[numThr] threshold;
  ...
```

So Eigen is throwing an error because the input and destination vectors are different sizes. These are checks that were only implemented in 2.27, which is why this is wasn't caught in the earlier version

**Comment by jpritikin** [comment] 2021-06-11 17:31
Ah yes, that seems correct. So why don't I get a good error message? Which stan module is responsible for reporting this kind of error?

**Comment by andrjohns** [comment] 2021-06-12 14:47
Because Stan isn't explicitly checking dimensions when assigning objects. Generally this will just result in the outcome object getting silently resized (a known bug which is still being worked on, [more info here](https://github.com/stan-dev/stanc3/issues/523)) but @SteveBronder refactored the handling of `data` and `transformed data` types to use Eigen `Map`, which doesn't allow resizing and so the error is thrown.

**Comment by SteveBronder** [comment] 2021-06-12 16:46
Hmm, maybe we should have some simple function on the rhs of statements that validates the size is correct then passes the object through to then be assigned

**Comment by rok-cesnovar** [comment] 2021-06-12 17:41
This does go through an assign. 
```stan
vector[numThresholds] truncPoints = ordinalTruncPoints(outcome);
```
is translated to 
```cpp
assign(truncPoints, ordinalTruncPoints(outcome, pstream__),
```
and those should validate before assigning I guess?

**Comment by SteveBronder** [comment] 2021-06-14 16:51
Oh hmm, so fixing this everywhere would break some thing in rstanarm, which in local blocks does assign the wrong dimensions to an array of vectors on purpose. Let me think about this, because yeah we def do not want users to see Eigen errors. Maybe we could have a specific assign we call in the model constructor that does these checks but then doesn't do it in `log_prob`

**Comment by rok-cesnovar** [comment] 2021-06-14 17:06
Is the thing in rstanarm a “feature” and not a bug? As in it need this to work?

**Comment by SteveBronder** [comment] 2021-06-14 17:10
Yeah it's a "feature"

**Comment by rok-cesnovar** [comment] 2021-09-10 08:39
Closing this here as this isnt realy a Cmdstan interface issue, rather an issue in the Stan repo, where we have an issue for this: https://github.com/stan-dev/stan/issues/3063

**Closed by rok-cesnovar** 2021-09-10 08:39 UTC
