### ISSUE TITLE
No supported way to build static binaries

### ISSUE THREAD

**Issue by hugbubby** [stan-dev/cmdstan#779] opened 2019-12-09 00:59 UTC
#### Summary:
I am accessing my stan program from inside a docker container and would like the ability to compile it as a standalone binary, rather than having to include the associated libraries wherever it goes.

#### Description:
I am currently using cmdstan inside a docker container in a production environment. One of the problems I have is that when I build my cmdstan binaries and move them, I also have to make
move the entire cmdstan repo, rather than placing my stan binary in an alpine docker container
and being done with it. This means I'm also lugging around a git repository of the cmdstan and
stan code, and unnecessarily increase the size of my docker container. While some of my burden
not entirely necessary (I could just figure out what libraries it is loading and copy only those), it
would be nice if there were an option for cmdstan to produce a binary I could just plop in and forget about.

#### Current Version:
v2.21.0

**Comment by mitzimorris** [comment] 2019-12-09 02:34
Not quite understanding what you mean by a "standalone binary".
E.g. - you can compile file `examples/bernoulli/bernoulli.stan` via command:
```
> make examples/bernoulli/bernoulli
```
the resutling binary is a standalone program that you can copy or move as you wish.

**Comment by wds15** [comment] 2019-12-09 05:43
Currently you have to link dynamically the Intel tbb to get a Stan program to work. As I understand you want to move a compiled Stan model into docker. The tbb is linked by default using rpath which hardcodes the tbb link path. You should be able to link the tbb yourself which can the place where you like. Does that make sense? It would be helpful if you provide a git repo with the Dockerfiles and its auxiliary files to run it.

**Comment by wds15** [comment] 2019-12-10 10:48
For the purpose of this issue...we can close it, i think. There is no supported way to end up with a static binary. The only action one could take is to review the doc for having a running stan exectuable model with the minimal set of binaries which means to install the tbb.

@mitzimorris thoughts?

**Comment by mitzimorris** [comment] 2019-12-10 13:13
is it possible to use the math lib v 2.20 which doesn't include the Intel TBB?

**Comment by mitzimorris** [comment] 2019-12-10 13:20
I think that @hugbubby has a valid use case here and I think that we need to find a way to address this, so no, I don't think we should close this issue.

**Comment by seantalts** [comment] 2019-12-10 13:31
@hugbubby were you asking to deploy a single compiled model inside the
docker container? Or the entirety of cmdstan with its ability to compile
new models?

**Comment by hugbubby** [comment] 2019-12-13 07:32
@wds15 Yes ,there is no supported way, which is why I am asking for a way. 

@seantalts A single compiled model. I personally have no need to compile more models in my docker container, though I see why you might want to do that; I'm using the one I've created to do inference in a production environment, and don't want to have to lug around the whole git repo.

**Comment by wds15** [comment] 2019-12-13 10:32
@hugbubby Well, you can use 2.20 if you want all static model binaries. With 2.21 and going forward there is no supported way for a fully static model binary. You will always have to link dynamically with the Intel TBB.

So what you can do is:
- configure a TBB build by yourself (or you could just take the Intel binaries if these work for you)
- setup cmdstan to use your provided TBB
- then compile the model
- place the model binary and the Intel TBB in the docker image

Would that work for you?

**Comment by hugbubby** [comment] 2019-12-13 22:47
> @hugbubby Well, you can use 2.20 if you want all static model binaries. With 2.21 and going forward there is no supported way for a fully static model binary. You will always have to link dynamically with the Intel TBB.
> 
> So what you can do is:
> 
>     * configure a TBB build by yourself (or you could just take the Intel binaries if these work for you)
> 
>     * setup cmdstan to use your provided TBB
> 
>     * then compile the model
> 
>     * place the model binary and the Intel TBB in the docker image
> 
> 
> Would that work for you?

It works for a certain definition of work; why is there an insistence on demanding the binary be dynamically compiled? I can actually build a statically compiled binary by modifying the internal makefiles; I just created this issue because I'd like to see a configuration option in the local makefile to do this automatically.

**Comment by wds15** [comment] 2019-12-14 05:54
The Intel TBB strongly discourages to be used as static library. They don’t even document how one can link statically against it. This is why we do not support it. I think we can close the issue. I am absolutely against going with static linking against the tbb given that is so much discouraged. That’s not my call.

I also don’t ses any issue with what I suggest. You endup getting a docker container with minimal binaries.

**Comment by mitzimorris** [comment] 2019-12-14 18:52
would it be possible to use an Intel docker container that supports TBB?
https://docs.nersc.gov/programming/shifter/intel/

**Comment by hugbubby** [comment] 2019-12-23 23:50
> would it be possible to use an Intel docker container that supports TBB?
> https://docs.nersc.gov/programming/shifter/intel/

I made the decision to use Clear Linux docker containers for their speed and explicit support of TBB. This situation is not without difficulty; I now have to wait for heroku to build the stan binary from scratch every time a new version of the service is pushed, but doing a clean from-ground-zero build also retains its upsides from a consistency perspective.

**Closed** 2019-12-23 23:51 UTC

**Comment by bob-carpenter** [comment] 2019-12-25 20:45
Thanks for reporting back on your resolution of this and for closing the issue.  This issue will probably come up for others who want to fully encapsulate the Stan environment.

**Comment by maedoc** [comment] 2020-08-27 19:18
I don’t see a resolution here (did I miss something?), and I don’t think the reasoning about dynamically linking TBB ([link](https://www.threadingbuildingblocks.org/faq/there-version-tbb-provides-statically-linked-libraries)) applies here, since we’re talking about standalone executables. 

In the discussion of reproducibility on discourse ([link](https://discourse.mc-stan.org/t/different-brms-behaviors-between-a-docker-image-and-the-same-image-imported-in-singularity/17638/13)) it would be helpful to have a static binary to eliminate sources of variability (at least for CmdStan not brms), since the lack static binaries leads to use of variable container runtime systems (among other things).

**Comment by mitzimorris** [comment] 2020-08-27 21:08
> I don’t see a resolution here (did I miss something?)

the resolution was this:

> I made the decision to use Clear Linux docker containers for their speed and explicit support of TBB. This situation is not without difficulty; I now have to wait for heroku to build the stan binary from scratch every time a new version of the service is pushed, but doing a clean from-ground-zero build also retains its upsides from a consistency perspective.
