### ISSUE TITLE
Running tests for OpenCL

### ISSUE THREAD

**Issue by demodw** [stan-dev/cmdstan#718] opened 2019-07-25 13:55 UTC
#### Summary:
When compiling cmdstan with OpenCL support, the following test fail:

```
python runCmdStanTests.py src/test/interface/opencl_test.cpp
```

See screenshot for the exact message. Unfortunately I cannot copy the error out from the server.
![Screen Shot 2019-07-25 at 15 44 31](https://user-images.githubusercontent.com/5146736/61879346-25719f00-aef3-11e9-9ae0-a6d27b87d9ac.png)

Oddly enough, the math-stan test, 

```
./runTests.py test/unit -f opencl
```

runs with no errors. 

I can compile and execute other Stan models no problem, with the exception that the GPU does not seem to be utilized when running a logistic regression. But this could maybe be because the routines described in https://github.com/bstatcomp/gpu-stan-paper-materials are not yet enabled for GLMs (?). 

#### Additional Information:
Operating system: CentOS v7.5
GPU: Tesla V100
OpenCL version: 1.2
CUDA version: 9.2

#### Current Version:
v2.20.0

**Comment by rok-cesnovar** [comment] 2019-08-05 18:35
First of all sorry for the late reply, I was not getting notifications for cmdstan issues. 

Anywaysm if you havent solved the issue. Could you post the contents of the make/local file?

> But this could maybe be because the routines described in https://github.com/bstatcomp/gpu-stan-paper-materials are not yet enabled for GLMs (?)

Yes, GPU GLMs have not been merged to develop yet, hopefully in the next month.

**Comment by rok-cesnovar** [comment] 2019-08-05 19:52
I was able to reproduce this error. Thank you for the report. 

It seems that building anything with STAN_OPENCL=true on 2.20 is not working. I am guessing this is related to the model base class PR. There arent any issue with the latest version of math. 

Is the OpenCL interface not being run on the cmdstan repo?

@SteveBronder any ideas?

**Comment by SteveBronder** [comment] 2019-08-05 20:06
I'll look into this tmrw but I'm pretty sure you are right on with the CRTP rebuild

**Comment by rok-cesnovar** [comment] 2019-08-05 20:29
I will also dig deeper tomorrow, for now what I have found is this. 

When linking the model `-lOpenCL` flag should be after `src/cmdstan/main.o`

This is how its called now:
```
g++ -std=c++1y -pthread -Wno-sign-compare   -I stan/lib/stan_math/lib/opencl_1.2.8  -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -DSTAN_OPENCL -DOPENCL_DEVICE_ID=0 -DOPENCL_PLATFORM_ID=0 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -D__CL_ENABLE_EXCEPTIONS -Wno-ignored-attributes               -lOpenCL  src/cmdstan/main.o stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_idas.a  examples/test_opencl_issue/GP.o -o examples/test_opencl_issue/GP
```
If `-lOpenCL` is placed behind main.o its all fine:
```
g++ -std=c++1y -pthread -Wno-sign-compare   -I stan/lib/stan_math/lib/opencl_1.2.8  -O3 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -DSTAN_OPENCL -DOPENCL_DEVICE_ID=0 -DOPENCL_PLATFORM_ID=0 -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -D__CL_ENABLE_EXCEPTIONS -Wno-ignored-attributes src/cmdstan/main.o -lOpenCL stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_4.1.0/lib/libsundials_idas.a  examples/test_opencl_issue/GP.o -o examples/test_opencl_issue/GP
```
Not sure exactly on where that could be changed in the cmdstan makefile structure, but its probably an easy fix for anyone more familiar with that.

**Comment by seantalts** [comment] 2019-08-06 17:03
Yep, we need to place all of the libraries like that behind the Stan objects. @mitzimorris would you have time to take a look at this regression? I can also take a look on Thursday if not. 

Can someone see if this is broken in develop? I ask because MPI had a similar issue and I dug into it (and wrote up my findings about how linkers work, haha) and fixed it here: https://github.com/stan-dev/cmdstan/pull/717.

**Comment by rok-cesnovar** [comment] 2019-08-07 08:21
> Can someone see if this is broken in develop?

I just went and checked, its not broken anymore on develop. Thank you for solving that! I guess we can close this issue then.

> (and wrote up my findings about how linkers work, haha)

Useful link :raised_hands:

**Closed** 2019-08-08 17:36 UTC
Labels: bug

**Comment by sean00002** [comment] 2020-01-12 07:16
I got a sligtly different problem here. When I try to run 
`python runCmdStanTests.py src/test/interface/opencl_test.cpp`
`clang++ -DSTAN_OPENCL_CACHE=true -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT    -I stan/lib/stan_math/lib/opencl_2.1.0  -I stan/lib/stan_math/lib/tbb_2019_U8/include -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include -I stan/lib/stan_math/lib/gtest_1.8.1/include -I stan/lib/stan_math/lib/gtest_1.8.1     -DBOOST_DISABLE_ASSERTS  -DSTAN_OPENCL -DOPENCL_DEVICE_ID=0 -DOPENCL_PLATFORM_ID=0 -DCL_HPP_TARGET_OPENCL_VERSION=120 -DCL_HPP_MINIMUM_OPENCL_VERSION=120 -DCL_HPP_ENABLE_EXCEPTIONS -Wno-ignored-attributes     -c -MT test/interface/opencl_test.o -MT src/test/interface/opencl_test.d -MM -E -MG -MP -MF src/test/interface/opencl_test.d src/test/interface/opencl_test.cpp`
the results above keep appearing and does not stop. 

MacOX catalina, cmdstan 2.21.0

**Comment by rok-cesnovar** [comment] 2020-01-12 08:09
Hi, the test was broken on the 2.21 release. Please clone the develop version of cmdstan from the repository and try to run it. There is also a new release coming in a week if you prefer that.

**Comment by sean00002** [comment] 2020-01-12 09:35
Thank you for your help! I just git clone the cmdstan from the GPU-based Parallel Computation Support for Stan paper. But I also have a question. Even through I am not using the GPU support functions like GLMs, any stan model I run should cause GPU activity? Since I am running one of my own model with GPU enabled, it gets slower than GPU disabled and there is no GPU usage by activity monitor.

**Comment by SteveBronder** [comment] 2020-01-12 22:35
Do you have `STAN_OPENCL=true` defined in make/local? It looks like that macro is not defined since no tests are running

**Comment by nesanders** [comment] 2020-01-12 22:47
Hi @SteveBronder,

Here is the text of my stan/lib/stan_math/make/local file in my clone of cmdstan:

> STAN_OPENCL=true
> OPENCL_DEVICE_ID=0
> OPENCL_PLATFORM_ID=0

I verified the device is ID=0 from `clifo`.

Is that the right location for it?

**Comment by seantalts** [comment] 2020-01-12 22:49
Put that in cmdstan/make/local instead :)
