### ISSUE TITLE
Error installing cmdstan in linux: it’s trying to use clang 

### ISSUE THREAD

**Issue by syclik** [stan-dev/cmdstan#586] opened 2017-11-27 19:09 UTC
Thanks, bmajoros (on Discourse)! See original thread: http://discourse.mc-stan.org/t/error-installing-cmdstan-in-linux-its-trying-to-use-clang/2620

#### Summary:
Even though the makefile appears to have g++ set as the compiler, it’s trying to call clang++, and that compiler is not installed.

#### Description:
CmdStan is not respecting the make options.
(I've seen this on another install.)

#### Reproducible Steps:
From a linux install without `clang++` installed, setting `CC=g++` or `CXX=g++` fails to run the `make build` target.

#### Current Output:
```
make: clang++: Command not found
```

#### Expected Output:
Everything should build.

#### Additional Information:
We changed the makefiles in Math and Stan. I think this issue stems from not handling the includes properly (but it could be anything really since it's make).

#### Current Version:
v2.17.0

**Comment by seantalts** [comment] 2017-12-07 15:05
I think this is a duplicate of https://github.com/stan-dev/cmdstan/issues/566

**Closed** 2017-12-14 16:58 UTC
