### ISSUE TITLE
Large values in data are not passed properly to Stan

### ISSUE THREAD

**Issue by martinmodrak** [stan-dev/cmdstan#1023] opened 2021-06-17 18:46 UTC
**Describe the bug**
When putting very large numbers (roughly around 1e9) into data, wrong walues may get passed to stan.

**To Reproduce**

```r
m_data <- cmdstan_model(write_stan_file("
data {
  real x;
}

model {
  print(x);
}
                                   "))

m_data$sample(chains = 1, iter_warmup = 1, iter_sampling = 0, fixed_param = TRUE,
         data = list(x = 3e8))
# Prints 3e8

m_data$sample(chains = 1, iter_warmup = 1, iter_sampling = 0, fixed_param = TRUE,
         data = list(x = 3e9))
# Prints  -1.29497e+09 
```

**Expected behavior**

Print 3e9 in the second case

**Operating system**
Windows 10

**CmdStanR version number**
0.4.0.9000 (just installed from GitHub)

**Comment by jgabry** [comment] 2021-06-17 20:04
I just transferred this issue from CmdStanR to CmdStan because I verified that the same problem happens when using CmdStan directly without CmdStanR. But I'm not sure if this is a CmdStan bug or if it should be moved to `stan-dev/stan`.

**Comment by mitzimorris** [comment] 2021-06-17 20:34
perhaps it's an I/O error.  is the input data for CmdStan in rdump or JSON format?
JSON doesn't distinguish between int and real, even so, 10^9 is should be w/in signed int range; OTOH, Windows might be using very short ints.

**Comment by jgabry** [comment] 2021-06-17 21:31
> perhaps it's an I/O error. is the input data for CmdStan in rdump or JSON format?

The example provided by Martin uses CmdStanR so it was using JSON (and I verified the JSON file was written correctly and also that the same problem occurs without CmdStanR just using CmdStan). 

> OTOH, Windows might be using very short ints.

This happens on my Mac and Martin's Windows computer so it doesn't seem to be related to the OS.

**Comment by mitzimorris** [comment] 2021-06-18 04:11
OK then,  will try to investigate.

**Comment by martinmodrak** [comment] 2021-06-18 07:38
Thanks for looking into this so quickly and for the additional verification!

**Comment by rok-cesnovar** [comment] 2021-06-18 13:04
The problem is that 3e9 is written in JSON or R dump as 3000000000 and that is parsed as an integer. If I place
```
x <- 3000000000
```
in a .data.R I get an error that its beyond int range.
In JSON however this:
```
{
  "x" : 3000000000
}
```
gets parsed as an integer and then seems to get converted to a double in some bizarre way. 

This however works fine
```
{
  "x" : 3e9
}
```

**Comment by jgabry** [comment] 2021-06-18 16:47
> gets parsed as an integer and then seems to get converted to a double in some bizarre way.

Any idea why it's a problem with 3e9 but doesn't seem to be a problem with 3e8?

**Comment by rok-cesnovar** [comment] 2021-06-18 16:59
I am guessing it has to do with the fact that 3e8 can be represented as an integer, but 3e9 can not be.

**Comment by alyst** [comment] 2021-08-10 23:40
Are the values as read by the JSON parser already incorrect?

**Comment by alyst** [comment] 2021-08-22 18:30
It looks like RapidJSON supports JSON schema.
Maybe it's possible to generate *SchemaDocument* DOM for the Stan model data block and provide the Schema to the JSON parser?

**Comment by rok-cesnovar** [comment] 2021-08-23 06:55
> Are the values as read by the JSON parser already incorrect?

Yeah, the logic is supposed to be that the parser first attempts parsing a number without a decimal point as an integer and once it recognizes the number is too big it parses its as a double. That seems to not be working as expected. I havent had the time to look into that. Will do ASAP.

> Maybe it's possible to generate SchemaDocument DOM for the Stan model data block and provide the Schema to the JSON parser?

That is doable as we can get info on types on data variables from stanc3. I would avoid this for now but we can start to think about it if there is no solution for the above.

**Comment by alyst** [comment] 2021-08-23 14:28
I've looked into the values that generate problems in my case.
For example
```json
{"qData": [2245935000, 2418300000] }
```

But it looks like at least rapidjson master parses them well (as Uint on my machine). But then in cmdstan I get `qData[sym1__] is -2.04903e+09` for the first value. And `qData[sym1__] is -1.87667e+09` for the second one.

**Comment by mitzimorris** [comment] 2021-08-23 14:37
> the logic is supposed to be that the parser first attempts parsing a number without a decimal point as an integer

adding a check that the sign is as expected would catch this problem, no?

**Comment by alyst** [comment] 2021-08-23 14:38
For me it looks like the cause of the error is at [json_data_handler.hpp#L228](https://github.com/stan-dev/cmdstan/blob/beb8764da84e25784aa8fe0d85648bae75221206/src/cmdstan/io/json/json_data_handler.hpp#L228) when unsigned is converted to signed. For the numbers from the example above this leads to the flip of the sign.

**Comment by rok-cesnovar** [comment] 2021-08-23 14:40
Integers in Stan are always signed. I guess we should not let rapidjson parse them to uint as uint is useless for the Stan use case.

**Comment by alyst** [comment] 2021-08-23 14:51
> Integers in Stan are always signed. I guess we should not let rapidjson parse them to uint as uint is useless for the Stan use case.

IIUC the [rapidjson code](https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/reader.h#L1732), it's not possible to change which handler would be called.
Unsigned number would be always processed by *Uint[64]* handlers. But the logic of the cmdstan handler could be changed.
Probably -- as it's already done for the reals -- the array has to be switched to *values_r* if the overflow would occur when converting unsigned to int.

**Closed** 2021-08-31 09:51 UTC
Labels: bug
