### ISSUE TITLE
cmdstan not compiling; multiple warnings

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstan#682] opened 2019-03-20 18:03 UTC
#### Summary:

CmdStan doesn't build.  I have the latest cmdstan on develop and have up-to-date stan and math lib.  

#### Description:

```
~/cmdstan(develop)$ git pull
Already up-to-date.
~/cmdstan(develop)$ make stan-update
git submodule update --init --recursive
~/cmdstan(develop)$ cd stan
~/cmdstan/stan((v2.19.0))$ make math-update
git submodule init
git submodule update --recursive
~/cmdstan/stan((v2.19.0))$ cd ..
~/cmdstan(develop)$ make -j4 O=0 ~/temp2/foo
clang++         /Users/carp/temp2/foo.o stan/src/stan/model/model_header.hpp.gch /Users/carp/temp2/foo.cpp src/cmdstan/main.cpp src/cmdstan/command.hpp src/cmdstan/arguments/argument_parser.hpp src/cmdstan/arguments/argument.hpp 
```

And then it goes on to list what looks like every file in our repo.   Then after many repetitions of

```
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```

it ends with

```
clang: error: cannot specify -o when generating multiple output files
make: *** [/Users/carp/temp2/foo] Error 1
~/cmdstan(develop)$ 

#### Current Version:
develop (2 pm EDT, 20 March 2019)

```
~/cmdstan(develop)$ clang++ --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by mitzimorris** [comment] 2019-03-20 18:26
did you do `make stan-update`?

this worked on my machine:
```
> cd github/stan-dev/cmdstan
> git checkout develop
> git pull
> make stan-update
> make clean-all
> make build
```

**Comment by bob-carpenter** [comment] 2019-03-20 19:56
OK, that worked.  You can see from my issue that I did exactly those steps with the addition of going into `cmdstan/stan` and updating the math lib.  I take it I shouldn't be doing that?

**Comment by bob-carpenter** [comment] 2019-03-27 20:39
This exact same thing happened to me again.  And this time I slavishly followed @mitzimorris's advice and it's still broken.

```
~/cmdstan(develop)$ git checkout develop
Already on 'develop'
~/cmdstan(develop)$ git pull
Already up-to-date.
~/cmdstan(develop)$ make stan-update
git submodule update --init --recursive
~/cmdstan(develop)$ git status
# On branch develop
nothing to commit, working directory clean
~/cmdstan(develop)$ make clean-all
rm -f -r doc
cd src/docs/cmdstan-guide; rm -f *.brf *.aux *.bbl *.blg *.log *.toc *.pdf *.out *.idx *.ilg *.ind *.cb *.cb2 *.upa
rm -f -r test
rm -f 
rm -f 
  removing dependency files
  cleaning sundials targets
rm -f 
rm -f -r bin
rm -f stan/src/stan/model/model_header.hpp.gch
~/cmdstan(develop)$ mk ~/temp2/foo
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare      -O0 -I src -I stan/src -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include    -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION     -c -MT src/cmdstan/stanc.o -MM -E -MG -MP -MF src/cmdstan/stanc.d src/cmdstan/stanc.cpp

...pages and pages of file names ...

b/boost_1.69.0/boost/date_time/adjust_functors.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/wrapping_int.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/date_generators.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/date_clock_device.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/date_iterator.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/time_system_split.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/time_system_counted.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/time.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/posix_time/date_duration_operators.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/posix_time/posix_time_duration.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/posix_time/time_period.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/time_iterator.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/date_time/dst_rules.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/diagnostic_information.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/get_error_info.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/error_info_impl.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/type_info.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/shared_ptr.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/info.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/to_string_stub.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/to_string.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/is_output_streamable.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/object_hex_dump.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/current_exception_cast.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception_ptr.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/exception_ptr.hpp stan/lib/stan_math/lib/boost_1.69.0/boost/exception/detail/clone_current_exception.hpp         -o /Users/carp/temp2/foo
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]

... continues ad nauseum ....

clang: error: cannot specify -o when generating multiple output files
make: *** [/Users/carp/temp2/foo] Error 1
~/cmdstan(develop)$ 
```

I have no idea how to tackle this problem.

**Comment by seantalts** [comment] 2019-03-27 20:42
I had this same issue: https://github.com/stan-dev/cmdstan/issues/668

**Comment by bob-carpenter** [comment] 2019-03-27 21:09
Commenting out:

```
# -include $(MATH)make/dependencies
```

in the cmdstan makefile managed to get things building again with the current develop version.  

Should this just be removed from the makefile if it's causing problems?  If not, how do I fix without editing the makefile?

**Comment by syclik** [comment] 2019-03-27 21:34
This is failing with building Boost. I’ve seen it pop up and disappear on its own, but haven’t been able to track it down to something repeatable. Mind pasting what’s in your `make/local`? Maybe that would clue us into some condition that would cause it to fail. 

@wds15: any ideas on when Boost fails to build?

**Comment by syclik** [comment] 2019-03-27 21:36
@bob-carpenter: I don’t know if commenting out dependencies actually fixes it. I believe I have the same compiler, so I’ll try to build from scratch tonight.

**Comment by bob-carpenter** [comment] 2019-03-27 21:40
Commenting out that dependency made mine work. But there's so much state floating around, I wouldn't bet that's what fixed it.

**Comment by syclik** [comment] 2019-03-27 22:15
I’ve seen it go away by building a second time. But I’ve seen it fail there
before. I definitely believe that there is a condition where it doesn’t
build successfully.

I'll try to see if I can reproduce it by being systematic and trying to
make it fail. My guess is that this in our building of Boost, but that's
just a guess.

Do you have any instructions for MPI inside your make/local? If those
aren't there, we shouldn't be building boost at all.

**Comment by syclik** [comment] 2019-03-28 00:30
@bob-carpenter, what's in your `foo.stan`?

**Comment by syclik** [comment] 2019-03-28 01:32
So... I spent a little time on it and couldn't reproduce the failure. A few things:

- the warnings are coming from building Boost. I've tried looking for ways to squash it, but I can't find a decent one. If you want to run that part separately, run `make build-mpi`
- I don't know why you're building Boost right now. If things are cleaned out and you don't have a `make/local` file, then it shouldn't build Boost.

I started from a clean clone of CmdStan. There might be some state in the build that's incompatible between v2.18.1 and `develop`. When all the makefiles were rebuilt, I didn't focus on dealing with old objects that may have been lingering from before.

**Comment by bob-carpenter** [comment] 2019-03-28 16:52
Nothing in `make/local` but I've used `mk`, which is this:

```
alias mk="make -j4 CC=clang++ O=0"
```

`foo.stan` is this---I've just been using it to experiment with code generation.

```
model {
  matrix[2, 2] m;
  int a[3];
  for (i in 1:3)
    print(i);
  for (x in a)
    print(x);
  for (x in m)
    print(x);
}
```

**Comment by syclik** [comment] 2019-03-28 18:08
That's super-weird that it would trigger a build of Boost with that alias.

You might want to update your alias so it's:
alias mk="make -j4 CXX=clang++ O=0"

With v2.19.0, we've cleaned up the use of the compiler variable to just be
CXX for the C++ compiler.

**Comment by mitzimorris** [comment] 2019-07-18 19:30
closing for now - makefile has been since been updated twice.

**Closed by mitzimorris** 2019-07-18 19:30 UTC
Labels: bug, makefile
