### ISSUE TITLE
CmdStan CC ignored in Makefile

### ISSUE THREAD

**Issue by cfhammill** [stan-dev/cmdstan#569] opened 2017-09-12 23:20 UTC
#### Summary:
The current CmdStan install is broken if the user doesn't have clang installed. 

#### Description:
The CC var set in the makefile is overwritten https://github.com/stan-dev/cmdstan/blob/develop/makefile#L34, this includes the compiler options for the stan math lib which overrides CC to clang++

#### Proposed Solution
Change the default_compiler_options setting of CC to `?=`, and for good measure do that in the CmdStan makefile as well. Happy to PR if you think it will go through.

#### Current Version:
v2.17.0

**Comment by seantalts** [comment] 2017-09-20 01:16
Are you trying to set the CC in `/makefile` or in `make/local`?

**Comment by seantalts** [comment] 2017-09-20 01:21
Woops, think this is just a duplicate of https://github.com/stan-dev/cmdstan/issues/566 which has a lot more info. Closing.

**Closed by seantalts** 2017-09-20 01:21 UTC
