### ISSUE TITLE
Typo in help/arguments (`id`)

### ISSUE THREAD

**Issue by ariddell** [stan-dev/cmdstan#560] opened 2017-06-29 14:33 UTC
```
  id=<int>
    Unique process identifier
    Valid values: id > 0
    Defaults to 0
```
Default of 0 appears to be an invalid value. Is this supposed to be 1?

**Comment by sakrejda** [comment] 2017-06-29 15:04
This may be an interaction with the recent RNG pull request.

**Comment by rok-cesnovar** [comment] 2019-09-16 15:26
Duplicate of #531

**Closed by rok-cesnovar** 2019-09-16 15:26 UTC
