### ISSUE TITLE
fatal error: bracket nesting level exceeded maximum of 256

### ISSUE THREAD

**Issue by HJJ666** [stan-dev/cmdstan#1122] opened 2022-09-28 07:40 UTC
#### Summary:
error occurred when compiling my own Stan file

#### Description:
--- Translating Stan model to C++ code ---
bin/stanc  --o=examples/wt/wt.hpp examples/wt/wt.stan

--- Compiling, linking C++ code ---
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o examples/wt/wt.o examples/wt/wt.hpp
examples/wt/wt.hpp:21115:84: fatal error: bracket nesting level exceeded maximum of 256
                                                                    stan::math::add(
                                                                                   ^
examples/wt/wt.hpp:21115:84: note: use -fbracket-depth=N to increase maximum nesting level
1 error generated.
make: *** [examples/wt/wt] Error 1

#### Current Version:
v2.30.1

**Comment by WardBrian** [comment] 2022-09-28 13:20
You can follow the recommendation of the error and set `-fbracket-depth` to a higher number by adding the following like to a file `<cmdstan-folder>/make/local`

```make
CXXFLAGS+= -fbracket-depth=1024
```

See [previous forum discussion](https://discourse.mc-stan.org/t/error-compiling-brms-model/28658)

**Comment by HJJ666** [comment] 2022-09-29 01:55
> You can follow the recommendation of the error and set `-fbracket-depth` to a higher number by adding the following like to a file `<cmdstan-folder>/make/local`
> 
> ```makefile
> CXXFLAGS+= -fbracket-depth=1024
> ```
> 
> See [previous forum discussion](https://discourse.mc-stan.org/t/error-compiling-brms-model/28658)

Thanks a lot. 
I have changed the index of the file (CmdStan-2.20.1/make/local.example) following like:

#Adding other arbitrary C++ compiler flags
#CXXFLAGS+= -fbracket-depth=1024

While it seems no effect, and the same fatal error occurred once again

**Comment by HJJ666** [comment] 2022-09-29 02:24
> The file needs to be called `make/local`. If you want to use the example you need to rename it.
> 
> Additionally, a `#` indicates a comment to be ignored. Have the line start without it

Thanks for your help! I am sorry that I ignore the annotation of the local.example file and it works out now.
However, the new error occurred like following:


clang++ -fbracket-depth=1024 -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o examples/wt/wt.o examples/wt/wt.hpp
In file included from examples/wt/wt.hpp:1:
In file included from stan/src/stan/model/model_header.hpp:4:
In file included from /Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/stan/math.hpp:19:
In file included from /Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev.hpp:4:
In file included from /Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22:
In file included from /Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Dense:1:
In file included from /Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/lib/eigen_3.3.9/Eigen/Core:445:
/Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/CoreEvaluators.h:100:5: fatal error: recursive template instantiation exceeded maximum depth of 1024
  : evaluator<T>
    ^
/Users/hjj/Desktop/cmdstan-2.30.1/stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/CoreEvaluators.h:100:5: note:



I noticed it should be reset the template instantiation while I do not know how to set this recursive template index.

**Comment by WardBrian** [comment] 2022-09-29 02:27
Are you able to share the model which is triggering this?

**Comment by HJJ666** [comment] 2022-09-29 02:50
> Are you able to share the model which is triggering this?

[test.stan.zip](https://github.com/stan-dev/cmdstan/files/9670424/test.stan.zip)

The model  file is shared. Thanks for your help!

**Comment by WardBrian** [comment] 2022-09-29 13:19
I'm not able to compile that model due to syntax errors. It seems rather complicated, is it from a package like `brms`? 

That said, the error you're getting was part of what caused us to release 2.30.1, are you sure you're not still using 2.30.0?

**Comment by HJJ666** [comment] 2022-09-29 14:26
> I'm not able to compile that model due to syntax errors. It seems rather complicated, is it from a package like `brms`?
> 
> That said, the error you're getting was part of what caused us to release 2.30.1, are you sure you're not still using 2.30.0?
It  is generated from arviz package and this is an example model that I am studying recently and I would like to compile it by cmdstan (v.2.30.1 download via GitHub). Could you please give me some advices of compiling this model?

**Comment by bob-carpenter** [comment] 2022-09-29 14:52
@HJJ666:  If this model is being generated by arViz, you should file an issue in their repo.  There's not much we can do if a package that's not part of the Stan project is generating ill-formed Stan models.  So I'm closing this issue.  If it turns out that the model was generated by something within the Stan project, we can re-open an issue in whatever repository is generating the model.

**Closed by bob-carpenter** 2022-09-29 14:52 UTC

**Comment by HJJ666** [comment] 2022-09-30 02:08
> @HJJ666: If this model is being generated by arViz, you should file an issue in their repo. There's not much we can do if a package that's not part of the Stan project is generating ill-formed Stan models. So I'm closing this issue. If it turns out that the model was generated by something within the Stan project, we can re-open an issue in whatever repository is generating the model.

Ok, thanks for your help

**Comment by HJJ666** [comment] 2022-09-30 06:27
> I am not able to give more advice without being able to compile the model myself. The errors I get start on line 6:
> 
> ```
> 	vector[N] pairwise_interaction_Bacteroidetes_space_vadinHA17_D_0__Bacteria;D_1__Firmicutes;D_2__Clostridia;D_3__Clostridiales;D_4__Clostridiaceae_space_1;
> ```
> 
> the semicolons lead to errors since `D_1__Firmicutes` is not a declaration but appears in the data block.


Thank you! I have found the problem and it is mainly correlated to my filter set-up. I exchange the model to the top 10 species this model could be compiled well by cmdstan(v.2.30.1) while the top 20 is not. I guess it is possibly related to the set-up recursive template instantiation of the Math module. Could you please help me have a look at the ex3 model in the zip file (the ex2 model is able to be well compiled now)? Thanks for your help!

[ex_test.zip](https://github.com/stan-dev/cmdstan/files/9681314/ex_test.zip)

**Comment by bob-carpenter** [comment] 2022-09-30 14:21
This is occurring because whatever is generating that code is nesting brackets more than 256 deep in the generated C++ code.  

You can set bracket depth in the build process.  Searches online for clang++ suggest `-fbracket-depth=512`, which you will have to pass as an option to CmdStan's make process. 

If you have expressions nested 256 deep, you're going to have bigger problems than C++ compiling.  If you think you have a simple model that shouldn't be generating outrageous code like this, I would suggest taking it up with whatever project is generating that code.  This is not a bug or issue for Stan per se.

**Comment by WardBrian** [comment] 2022-09-30 14:29
I think the issues are all stemming from the sum which represents the mean of the normal distribution in the likelihood. That line in `ex3.stan` is 54126 characters long and probably includes too many terms for Eigen to properly handle the expression templating, which is why the C++ compiler gives up. 

I suspect you could fix this problem (in the sense of getting the C++ to compile) by splitting that sum into several parts and then adding up those parts. But, as Bob mentions, this will still be a strange model, just perhaps one which will compile.
